FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY package*.json ./
RUN npm install --omit=dev

COPY server ./server
RUN mkdir -p uploads

ENV NODE_ENV=production
EXPOSE 10000

CMD ["node", "server/entrypoint.js"]
